# Generated by Django 2.2.2 on 2019-06-17 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='survey_answer_id',
            new_name='survey_answer',
        ),
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='survey_id',
            new_name='survey',
        ),
    ]
